/*******************************************  
CSE572 S19 Final
EXAM Question 4 
006704029
*******************************************/

DROP TABLE Clincs CASCADE CONSTRAINTS;
CREATE TABLE Clincs (
	ClincNo	CHAR(4),
	Addr  VARCHAR2(30),
	Tel   CHAR(10),
	StaffNo	CHAR(9),	
	OwnerNo CHAR(9),
	PetNo   CHAR(9),
	CONSTRAINTS Clincs_ClincNo_PK PRIMARY KEY (ClincNo)
);


DROP TABLE Staff CASCADE CONSTRAINTS;
CREATE TABLE Staff (
	staffNo	CHAR(9),
        Name    VARCHAR2(20),
	Addr  VARCHAR2(30),
	Tel   CHAR(10),
        DateOfBirth CHAR(11),
        Sex CHAR(1),
        SSN CHAR(9),
        Position VARCHAR2(10),
        Salary   NUMBER(7,2),
	MGRname    VARCHAR2(20),	
	ClincNo	CHAR(4),
	CONSTRAINTS Staff_staffNo_PK PRIMARY KEY (staffNo)
);


DROP TABLE PetOwner CASCADE CONSTRAINTS;
CREATE TABLE PetOwner (
	OwnerNo  CHAR(9),
	OwnerName VARCHAR2(20),	
	Addr  VARCHAR2(30),
	Tel   CHAR(10),
	PetNo CHAR(9),
	CONSTRAINTS PetOwner_OwnerNo_PK PRIMARY KEY (OwnerNo)
);


DROP TABLE Pets CASCADE CONSTRAINTS;
CREATE TABLE Pets (
	PetNo CHAR(9),
	PetName VARCHAR2(20),
	Type VARCHAR2(10),
        DESCS VARCHAR2(20),
	DateOfBirth CHAR(11),
        RegDate CHAR(11),
        Status VARCHAR2(10),
        Detail VARCHAR2(20),
        OwnerNo  CHAR(9),
	CONSTRAINTS Pets_PetNo_PK PRIMARY KEY (PetNo)
);

DROP TABLE Examinations CASCADE CONSTRAINTS;
CREATE TABLE Examinations (
	examNo	CHAR(10),
	PetName VARCHAR2(20),	
	PetNo CHAR(9),
        Type VARCHAR2(10),
        Diagnosis VARCHAR2(30),
        VetName VARCHAR2(20),
        staffNo	CHAR(9),
        CONSTRAINTS Examinations_examNo_PK PRIMARY KEY (examNo)
);

DROP TABLE SickPet CASCADE CONSTRAINTS;
CREATE TABLE SickPet (
	PetNo CHAR(9),
	examNo	CHAR(10),
        OwnerNo  CHAR(9),
        CONSTRAINTS SickPet_PetNo_examNo_PK PRIMARY KEY (PetNo,examNo)
);

ALTER TABLE Clincs
	ADD CONSTRAINTS Clincs_staffNo_FK FOREIGN KEY (staffNo) 
	REFERENCES Staff(staffNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Clincs
	ADD CONSTRAINTS Clincs_OwnerNo_FK FOREIGN KEY (OwnerNo) 
	REFERENCES PetOwner(OwnerNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Clincs
	ADD CONSTRAINTS Clincs_PetNo_FK FOREIGN KEY(PetNo) 
	REFERENCES Pets(PetNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;	

ALTER TABLE Staff
	ADD CONSTRAINTS Staff_ClincNo_FK FOREIGN KEY (ClincNo) 
	REFERENCES Clincs(ClincNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;	

ALTER TABLE PetOwner
	ADD CONSTRAINTS PetOwner_PetNo_FK FOREIGN KEY (PetNo) 
	REFERENCES Pets(PetNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;	
		
ALTER TABLE Pets
	ADD CONSTRAINTS Pets_OwnerNo_FK FOREIGN KEY (OwnerNo) 
	REFERENCES PetOwner(OwnerNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Examinations
	ADD CONSTRAINTS Examinations_PetNo_FK FOREIGN KEY (PetNo) 
	REFERENCES Pets(PetNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Examinations
	ADD CONSTRAINTS Examinations_staffNo_FK FOREIGN KEY (staffNo) 
	REFERENCES Staff(staffNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE SickPet
	ADD CONSTRAINTS SickPet_PetNo_FK FOREIGN KEY (PetNo) 
	REFERENCES Pets(PetNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE SickPet
	ADD CONSTRAINTS SickPet_examNo_FK FOREIGN KEY (examNo) 
	REFERENCES Examinations(examNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE SickPet
	ADD CONSTRAINTS SickPet_OwnerNo_FK FOREIGN KEY (OwnerNo) 
	REFERENCES PetOwner(OwnerNo)
	ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;


	
	
	
